name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14', '16', '>=20']

    steps:
    - uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node_version}}
    
    - name: Install dependencies
      run: npm run install
    
    - name: Test application
      run: npm run test
      
    - name: Build application
      run: npm run build
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag front-director:$(date +%s)
      
    # - name: Build-DB
    #   run: docker-compose build
      
    # - name: start docker
    #   run: docker-compose up -d

